#mp.messaging.incoming.words-in.auto.offset.reset=earliest
#mp.messaging.incoming.words-in.topic=words
#mp.messaging.outgoing.words-out.topic=words

quarkus.flyway.migrate-at-start=true
quarkus.flyway.validate-on-migrate=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=admin
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/smonotp

# In dev, disable OTLP trace export when no local collector is running on 4317.
%dev.quarkus.otel.traces.exporter=none


# Kafka bootstrap
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:9092

# OUTGOING channel
mp.messaging.outgoing.order-created.connector=smallrye-kafka
mp.messaging.outgoing.order-created.topic=order-events
mp.messaging.outgoing.order-created.value.serializer=org.apache.kafka.common.serialization.StringSerializer
``
